### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by felipeegasneris** [LeftValues/leftvalues.github.io#1]
hi! your quiz is awesome, but I and my friends are  Spanish spoken people, I think this quiz needs an internationalization module to bring the left political spectre to all the world! greeting from Chile, Southamerica, Socialismo o Barbarie!

**Comment by LeftValues** [comment]
I would love to have other non-English versions in the future, though I would need help translating.

**Comment by xbony2** [comment]
Because this project is still being very actively worked with and perfected, I assume it will be a bit until a system for translation can be created.

**Comment by Liszur** [comment]
If you work it out, i and some of my friends are happy to make a Hungarian translation. :)

**Comment by qwertygc** [comment]
I can find friends for translate in french.

**Comment by ZerataX** [comment]
We now have an internationalization module and already a german translation and 90% ready french translation, see https://github.com/LeftValues/leftvalues.github.io/pull/4
To localize just make a pull request for the following files:
  - `ideologies.js`
  - `questions.js`
  - `i18n.js`

**Comment by felipeegasneris** [comment]
i can translate to spanish, this weekend i gonna work on that!
