### ISSUE TITLE
Why only GitHub, owned by MS?

### ISSUE THREAD

**Issue by amirisbrown** [LeftValues/leftvalues.github.io#10]
Why is this repository not on _all_ GITs, such as GitLab, Ubuntu One, BitBucket etc? I don't see how GitHub nor the[ TLD of io](https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/) represents the embodiment of "Left Values" though the test tries to capture such data itself for "fun". I'd like to see this on more open and free GIT platforms, if values be true to the game.

I am unable to review the source code as I don't yet know JavaScript, btw.

**Comment by LeftValues** [comment]
GitLab uses the .io TLD as well. It is simply easier to do this through GitHub regardless of personal views.
