### ISSUE TITLE
Unclear immigration question

### ISSUE THREAD

**Issue by xbony2** [LeftValues/leftvalues.github.io#18]
```
Mass foreign immigration policies are naïve and should not be implemented.
```

I have no idea if said policies mean they are allowing mass immigration or trying to prevent mass immigration. I'm guessing the earlier but the question is a bit ambiguous.

**Comment by campaignupgrade** [comment]
I had to consider that no policies at all would be de facto open immigration. 

But "Mass foreign immigration" suggests a lot of immigration. 

So yeah... ambiguous. 

I think it means "Policies allowing mass foreign immigration are naïve and should not be implemented."

**Comment by sparkz9502** [comment]
It should be more clear now: "Policies that enable mass immigration are naïve and should not be implemented."
