### ISSUE TITLE
It is unclear what is meant by "violence" in the quiz

### ISSUE THREAD

**Issue by krasnovian** [LeftValues/leftvalues.github.io#28]
"Violence" isn't clearly defined in the quiz questions. Political philosophy has a wealth of literature about the nature of violence and the state's role in exercising legitimate violence as the will of the people. So when I'm asked about asking people to "peacefully" give up their wealth it's unclear if you mean just like asking them nicely or actually passing a law, which could be construed as a form of violence since the threat is jail or some other punishment if they disobey the law.

It would be great if this and maybe other terms (I didn't get that far into the quiz) could be defined somewhere or if the questions could be clarified a little more.

**Comment by LeftValues** [comment]
That question in particular is related to more utopian early forms of socialism. I may add some sort of annotation to questions to explain them in more depth.
