### ISSUE TITLE
please add Socialism with Chinese Characteristics

### ISSUE THREAD

**Issue by neng245547874** [LeftValues/leftvalues.github.io#36]

**Comment by cijiugechu** [comment]
Obviously,it is a right-wing ideology.

**Comment by 2020LeftistStrikeBack** [comment]
No, so-called "Socialism with Chinese Characteristics" is actually State Capitalism with Stalinist social control.

**Comment by Evolto2019** [comment]
It is Authoritarian Capitalism or anything but socialism.

**Comment by liyishuai** [comment]
"Socialism with Chinese Characteristics" has different versions: pre-Xi era vs The New Era. Which one did you mean?

**Comment by huopd** [comment]
Socialism with Chinese characteristics = Capitalism with Chinese characteristics

**Comment by LeftValues** [comment]
This won't be added.

**Comment by heacsing** [comment]
典中典
