### ISSUE TITLE
Hi! I want translate it, can you heeeelp?

### ISSUE THREAD

**Issue by ChessmasterHex** [LeftValues/leftvalues.github.io#37]
I want translate it! Where I can found the final-translator-&-credits-link policies? We have it? 

If not, i need more helps, so.
I never tranlate a project in github. What can I begin to search for?

Ty u all!

e

**Comment by ZerataX** [comment]
Hey,

we sadly don't yet have any contribution guidelines or other policies really.
Currently we don't use any external tools so you have to work directly with github, but generally there are 3 files you should look at:

- [i18n.js](https://github.com/ChessmasterHex/leftvalues.github.io/blob/master/i18n.js)
- [ideologies.js](https://github.com/ChessmasterHex/leftvalues.github.io/blob/master/ideologies.js)
- [questions.js](https://github.com/ChessmasterHex/leftvalues.github.io/blob/master/questions.js)

to test this you could download/clone your repository and just open the `index.html` or try to set up github pages for your fork.

If you never worked with git/github it's probably a good idea to look into that a little bit, but using the webinterface should be fairly straightforward.

Generally you have edit e.g. i18n.js and have something like this:
https://github.com/LeftValues/leftvalues.github.io/blob/78ad7a1566a89dc0d75c522c2eced551e52177d7/i18n.js#L20-L41

So now you would edit this to look like this:
```js
const languages = [ 
     { 
         "name": "english", 
         "code": "en" 
     }, 
     { 
         "name": "deutsch", 
         "code": "de" 
     }, 
     { 
         "name": "한국어", 
         "code": "ko" 
     }, 
     { 
         "name": "ру́сский", 
         "code": "ru" 
     }, 
     { 
         "name": "简体中文", 
         "code": "cn" 
     },
     {
         "name": "spanish",
         "code": "es"
     }
 ] 
```
most important here are the **,** that separate the values.

Hope that helps!

**Comment by ChessmasterHex** [comment]
Oh, yesh! Thank You for your help! 

 I am reading/studing the code and thinking what can I do!

Again, ty!

e

**Comment by ZerataX** [comment]
@ChessmasterHex we now have a website that should make this process a lot more straightforward: https://l10n.dmnd.sh/projects/leftvalues/leftvalues/

**Comment by ChessmasterHex** [comment]
> 
> 
> @ChessmasterHex we now have a website that should make this process a lot more straightforward: https://l10n.dmnd.sh/projects/leftvalues/leftvalues/

Tank You! I have used that tool an d like it a lot! Easy Busy! The translations that i kwbow almost over :)
