### ISSUE TITLE
A suggestion for better translation work

### ISSUE THREAD

**Issue by Jyunmau** [LeftValues/leftvalues.github.io#42]
I wonder is the original language in this project German？I suggest, to make translation more better, we should make the discribtion in original language as accuracy as possible, then native contributors in other language can note original distributions follow some fuzzy translations which situation is normal in non-alphabetic language such as Chinese, Japanese, Korean, etc. that could help a lot for readers.

**Comment by ZerataX** [comment]
english is the original
