### ISSUE TITLE
Closest match and Next closest matches is null

### ISSUE THREAD

**Issue by dakun666** [LeftValues/leftvalues.github.io#47]
https://leftvalues.github.io/results.html?a=39.7&b=73.5&c=76.7&d=53.6&e=60.4&f=44.4&g=56.3

**Comment by dakun666** [comment]
Am I not enough left value? HAHA

**Comment by xqm32** [comment]
Same here. :(

**Comment by zhaobean** [comment]
maybe we can roll back

**Comment by maoanran** [comment]
The same to me.

**Comment by maoanran** [comment]
A bug was introduced.

**Comment by ZerataX** [comment]
oof sorry about that but should be fixed now with #48
