### ISSUE TITLE
Contribution Guideline

### ISSUE THREAD

**Issue by ZerataX** [LeftValues/leftvalues.github.io#54]
We should probably write a Contribution Guideline and link to it in the README so people can see how to add translation etc.

BTW would also be neat to add 
![exp](https://user-images.githubusercontent.com/5024958/81000116-133f6c80-8e46-11ea-92c9-098a779554d1.png) these things here and maybe turn this account into a organization

Also see the general recommendations: https://github.com/LeftValues/leftvalues.github.io/community

**Comment by sparkz9502** [comment]
I've turned the LeftValues account into an organization and added a description. As far as the contribution guidelines, that is a good idea. We'll have to figure out the best way to explain the translation process.
