### ISSUE TITLE
Overview which question which values - possible?

### ISSUE THREAD

**Issue by robin-tunger** [LeftValues/leftvalues.github.io#7]
Hello there! Thank you for your work!
I found some of the questions irritating but in the end I was surprised my result fits pretty well.
In a loose group of activists we are comparing and discussing the quiz now.

Is it possible to get an overview of which values have effect on which question?
I am sure it is possible to work through all the code to find out, but I am not so used to this and I guess you have something like that anyway.

Thank you!

**Comment by robin-tunger** [comment]
Btw:My question aims on the issue of human overpopulation.
Looking at the order of the questions it seems to be a question of ecology. But shouldn't it rather be a question of conservatism?

**Comment by ZerataX** [comment]
you can check the effects here: https://github.com/LeftValues/leftvalues.github.io/blob/master/questions.js#L883
where 
  - **a:** Revolution vs. Reform
  - **b:** Scientific vs. Utopian
  - **c:** Central vs. Decentral
  - **d:** International vs. National
  - **e:** Party vs. Union
  - **f:** Production vs. Nature
  - **g:** Conservative vs. Progressive

**Comment by LeftValues** [comment]
> Btw: My question aims on the issue of human overpopulation.
> Looking at the order of the questions it seems to be a question of production/nature. But shouldn't it rather be a question of conservative/progressive?
> 
> ![grafik](https://user-images.githubusercontent.com/26470902/64133060-24763c00-cdd4-11e9-806d-10210ca9ccb0.png)
> 
> ![grafik](https://user-images.githubusercontent.com/26470902/64133124-6e5f2200-cdd4-11e9-9a5b-651042ac65e7.png)

Agreeing to the overpopulation question actually does increase your conservative score. The point of such a question in the production vs nature category is exactly to try and weed out the ecofascist types. You are not necessarily supposed to get 100% nature unless you are a full on ecofascist or extreme primitivist, just like how you wont get 100% national unless you are a full on ultranationalist.
