### ISSUE TITLE
Seemingly Blocked by GFW in Mainland China

### ISSUE THREAD

**Issue by Scratchbin** [LeftValues/leftvalues.github.io#87]
This time my browser nearly always reports that "Connection Timed Out" and no visit works since I tried to check my result. Creepy since all visits I made in the past worked (at least in my mind). Therefore, I am afraid that the site may be blocked by GFW...

**Comment by Scratchbin** [comment]
*Although I know that this does not affect the site's development, this confuses me that having no ability using VPN things to visit it.*

**Comment by planetoryd** [comment]
@Scratchbin First day living in China ?

**Comment by Scratchbin** [comment]
I'm always in China since my birth.

**Comment by planetoryd** [comment]
@Scratchbin Ikr, close this issue. It's worthless

**Comment by Scratchbin** [comment]
Okay then.
